<?php

namespace Database\Seeders;

use App\Models\Recipe;
use App\Models\Trip;
use App\Models\VehicleModification;
use App\Services\FileUploadService;
use Database\Seeders\Demo\DemoContent;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Removes exactly what DemoContentSeeder created, and nothing else.
 *
 * Trips and recipes are matched on their demo slugs, modifications on their
 * names, and images by the hash of their deterministically generated bytes.
 * Anything you have written yourself is left alone - including a demo record
 * you have since edited, since editing does not change its slug.
 */
class DemoContentCleanupSeeder extends Seeder
{
    public function run(FileUploadService $uploads): void
    {
        $trips = Trip::withTrashed()
            ->whereIn('slug', array_column(DemoContent::trips(), 'slug'))
            ->get();

        $recipes = Recipe::withTrashed()
            ->whereIn('slug', array_column(DemoContent::recipes(), 'slug'))
            ->get();

        $modifications = VehicleModification::whereIn(
            'name',
            array_column(DemoContent::modifications(), 'name'),
        )->get();

        $files = DemoContentSeeder::seededFiles();

        if ($trips->isEmpty() && $recipes->isEmpty() && $modifications->isEmpty() && $files->isEmpty()) {
            $this->command?->info('No demo content found. Nothing to remove.');

            return;
        }

        DB::transaction(function () use ($trips, $recipes, $modifications, $files, $uploads): void {
            foreach ($trips as $trip) {
                // Force delete so campsites cascade rather than being orphaned.
                $trip->images()->detach();
                $trip->forceDelete();
            }

            foreach ($recipes as $recipe) {
                $recipe->forceDelete();
            }

            $modifications->each->delete();

            // Removes the stored object, its Image row and the File record.
            foreach ($files as $file) {
                $uploads->delete($file);
            }
        });

        $this->command?->info(sprintf(
            'Removed %d trips, %d recipes, %d modifications and %d images.',
            $trips->count(),
            $recipes->count(),
            $modifications->count(),
            $files->count(),
        ));
    }
}
